baseURL = 'https://github.com/Gambos/HaitianWang.github.io'
languageCode = 'en-us'
theme = 'PaperMod'
enableEmoji = true

[params]
title = 'Haitian Wang'
author = 'Yao'
description = "Let's have our first academic website!"